### ISSUE TITLE
Implement file server and file server API endpoints to store user account files

### ISSUE THREAD

**Issue by Luna-Klatzer** [SYP-AHIF-2023-24-25/SolarDoc#107]
Implement file server to store user account files i.e. presentations that then can be opened in the frontend.

To allows user to access the files, endpoints should be exposed that will then also be used in the frontend.

**Comment by Luna-Klatzer** [comment]
This issue should probably be implemented in the following way:

Since we already have a Phoenix server as a backend server and web socket solution it would make sense to also integrate this new file system API into its system. As such we can simply use the [automatic API generation by Phoenix](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Json.html#module-api-prefix), where we then simply create the `Files` module with a `File` database schema.

This scheme should at least contain the following fields:
- `file_name`: The name of the file.
- `last_edited`: The date it was last edited (datatype `naive_datetime`). The API for it should return a UNIX timestamp though i.e. number created from the naive datetime (See [ref](https://github.com/SYP-AHIF-2023-24-25/SolarDoc/blob/3d4b591f14b08ecaf693d89d140d878d654a812b/solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/editor_channel/editor_channel_json.ex#L26)).
- `created`: The date it was created. Should have the same datatype and API functionality as `last_edited`.
- `creator`: A foreign key/object which connects the file to the owner.

The remaining API functionality can be almost the same as the existing channel endpoint (including the OpenAPI/Swagger definition).

**Comment by LisaPich** [comment]
Implemented by #121 and will be released in `0.5.0`.
