### ISSUE TITLE
Implement generate share URL button for user presentations

### ISSUE THREAD

**Issue by Luna-Klatzer** [SYP-AHIF-2023-24-25/SolarDoc#117]
As we are implementing a file storage for users as explained in #107 and #108, a system for sharing such files/presentations with other users is necessary. Such a system would generate a token on the server side which includes the permissions that the creator grants the users possessing that token (used in combination with a specific endpoint/URL of course).

Note: If a user were to join with read & write permissions and there were already people editing the presentation, then the user would also automatically join that channel and be able to collaborate with them right away. To ensure this works right away, even if the user opens up a file with no other people currently accessing it, an empty channel will open just for them so that any user joining can join right away. In this case, due to the token issued and contained in the URL, no password would have to be granted.

**Comment by Luna-Klatzer** [comment]
This issue should probably be implemented in the following way:

Since we already have a Phoenix server as a backend server and web socket solution it would make sense to also integrate this new file system API into its system. As such we can simply use the [automatic API generation by Phoenix](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Json.html#module-api-prefix), where we then simply create the `Share` module with a `ShareURL` database schema.

This scheme should at least contain the following fields:
- `file`: The file that the share URL was issued for.
- `issued_at`: When the share URL was issued. (Datatype and API logic for datetimes explained [here](https://github.com/SYP-AHIF-2023-24-25/SolarDoc/issues/107#issuecomment-2010258122))
- `perms`: For now to make it rather simplistic, we will simply say `1` means `read` and `3` means `read & write`. This is to allow potential bit add & subtract permissions in the future, but for now it'll just be `1` (Binary: `0000 0001`) and `3` (Binary: `0000 0011`). This should be a short number.
- `expires_at`: The UNIX timestamp when the URL will expire. (See `issued_at` for timestamp handling) This should be in the API one year after `issued_at`.
- `expired`: A boolean field which will be `1` if expired and `0` if not. This is to allow us to manually disable URLs without having to delete them, which may be only rarely needed but something that's still useful.

The remaining API functionality can be almost the same as the existing channel endpoint (including the OpenAPI/Swagger definition).

**Comment by Kaede25** [comment]
Closed by: #125
