### ISSUE TITLE
New file keeps content from fromer file

### ISSUE THREAD

**Issue by Kaede25** [SYP-AHIF-2023-24-25/SolarDoc#147]
When creating a new file, the editor still shows the content from the old file. (In the local storage the content is correct it only gets displayed wrong)

**Comment by Luna-Klatzer** [comment]
Going to be fixed in a joint fix for #147, #150 and #152 as they are all related and stem from similar core issues.

**Comment by Luna-Klatzer** [comment]
Fixed by #154.
