### ISSUE TITLE
Share pop up has the wrong styling

### ISSUE THREAD

**Issue by Kaede25** [SYP-AHIF-2023-24-25/SolarDoc#149]
The pop up, which appears once a share URL needs to be created but the file isn't saved, is placed wrong. 
It should be placed like the channel view pop up.
(This should get fixed in **all** share URL pop ups!)

![image](https://github.com/SYP-AHIF-2023-24-25/SolarDoc/assets/86598092/839271b7-b017-4792-ad2f-25954b9362a7)

**Comment by Luna-Klatzer** [comment]
Fixed by #163 and c02aef1d585909f960f4675444d1a9b1f7ed3f46
