### ISSUE TITLE
Editor doesn't save latest change (only when another change is pushed on top of it)

### ISSUE THREAD

**Issue by Kaede25** [SYP-AHIF-2023-24-25/SolarDoc#150]
When editing a already saved file, the newest changes do not get saved. 
For example:
```adoc
= Snek

== sne
```
is what i have saved so far, if I now only add the missing 'k', it does not get saved. 
If I add more text, the last change will not get saved. For example in this case, the new 'k' does get saved, but the 'm' does not.

```adoc
= Snek

== snek

m
```

**Comment by Luna-Klatzer** [comment]
Going to be fixed in a joint fix for #147, #150 and #152 as they are all related and stem from similar core issues.

**Comment by Luna-Klatzer** [comment]
Fixed by #154.
