### ISSUE TITLE
Redirect to editor after logging in to access a ShareURL

### ISSUE THREAD

**Issue by Kaede25** [SYP-AHIF-2023-24-25/SolarDoc#162]
Redirect to the editor after logging in to access a ShareURL. 

Currently, the application simply directs to the profile page and does not remember the initial ShareURL accessed.

**Comment by Luna-Klatzer** [comment]
Related to #110

**Comment by Luna-Klatzer** [comment]
As #110 is now implemented, we can implement this with the new query parameter `returnTo`.

**Comment by Luna-Klatzer** [comment]
Fixed by #183.
