### ISSUE TITLE
Core AsciiDoc editor for editing and viewing files (monaco-editor)

### ISSUE THREAD

**Issue by LisaPich** [SYP-AHIF-2023-24-25/SolarDoc#22]
Create a base component for the file editor using [`microsoft/monaco-editor`](https://github.com/microsoft/monaco-editor).

### References

- https://github.com/SYP-AHIF-2023-24-25/SolarDoc/discussions/2

**Comment by Luna-Klatzer** [comment]
Implemented by #39
