### ISSUE TITLE
Report syntax errors or warnings for invalid Asciidoc code

### ISSUE THREAD

**Issue by Luna-Klatzer** [SYP-AHIF-2023-24-25/SolarDoc#56]
Report errors using the built-in monaco.js [`setModelMarkers` API](https://github.com/microsoft/monaco-editor/issues/1477#issuecomment-501220514), which can highlight errors or warnings such as:

- No space between title and content breaking reveal.js render step.
- Inconsistent listing style.

**Comment by Kaede25** [comment]
Implemented by #76
