### ISSUE TITLE
Add automatic API client generation for frontend based on backend Rest-API `openapi.json` file

### ISSUE THREAD

**Issue by Luna-Klatzer** [SYP-AHIF-2023-24-25/SolarDoc#57]
Implement an automatic process that generates an API client for the backend that can be used to interact with the backend without having to manually write any HTTP requests.

Since our backend already automatically generates an `openapi.json` file, only the generator needs to be set up in the `@solardoc/frontend` package.

Potential library that could do this for us:
- Fern ([Homepage](https://docs.buildwithfern.com/generate-sd-ks), [GitHub](https://github.com/fern-api/fern))

**Comment by Kaede25** [comment]
implemented by #64
